# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mstat_conversion_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(570, 571)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.vertical_layout.setObjectName("vertical_layout")
        self.convdata_table = QtWidgets.QTableWidget(Dialog)
        self.convdata_table.setObjectName("convdata_table")
        self.convdata_table.setColumnCount(0)
        self.convdata_table.setRowCount(0)
        self.vertical_layout.addWidget(self.convdata_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.beginconversion_button = QtWidgets.QPushButton(Dialog)
        self.beginconversion_button.setObjectName("beginconversion_button")
        self.horizontalLayout.addWidget(self.beginconversion_button)
        self.createmzml_check = QtWidgets.QCheckBox(Dialog)
        self.createmzml_check.setObjectName("createmzml_check")
        self.horizontalLayout.addWidget(self.createmzml_check)
        self.horizontalLayout.setStretch(0, 1)
        self.vertical_layout.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.vertical_layout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "MZML Conversion"))
        self.beginconversion_button.setText(_translate("Dialog", "Begin File Conversion"))
        self.createmzml_check.setText(_translate("Dialog", "Create MZML Files"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
