# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'binning_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(489, 99)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.uplim_label = QtWidgets.QLabel(Dialog)
        self.uplim_label.setObjectName("uplim_label")
        self.gridLayout_2.addWidget(self.uplim_label, 0, 4, 1, 1, QtCore.Qt.AlignRight)
        self.lowlim_input = QtWidgets.QLineEdit(Dialog)
        self.lowlim_input.setObjectName("lowlim_input")
        self.gridLayout_2.addWidget(self.lowlim_input, 0, 3, 1, 1)
        self.lowlim_label = QtWidgets.QLabel(Dialog)
        self.lowlim_label.setObjectName("lowlim_label")
        self.gridLayout_2.addWidget(self.lowlim_label, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.bin_size_label = QtWidgets.QLabel(Dialog)
        self.bin_size_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bin_size_label.setObjectName("bin_size_label")
        self.gridLayout_2.addWidget(self.bin_size_label, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.bin_size_input = QtWidgets.QLineEdit(Dialog)
        self.bin_size_input.setObjectName("bin_size_input")
        self.gridLayout_2.addWidget(self.bin_size_input, 0, 1, 1, 1)
        self.uplim_input = QtWidgets.QLineEdit(Dialog)
        self.uplim_input.setObjectName("uplim_input")
        self.gridLayout_2.addWidget(self.uplim_input, 0, 5, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setColumnStretch(3, 2)
        self.gridLayout_2.setColumnStretch(4, 1)
        self.gridLayout_2.setColumnStretch(5, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change data binning options"))
        self.uplim_label.setText(_translate("Dialog", "Upper Limit"))
        self.lowlim_label.setText(_translate("Dialog", "Lower Limit"))
        self.bin_size_label.setText(_translate("Dialog", "Bin Size"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
