# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conversion_options_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(337, 182)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 5)
        self.manualwindow_label = QtWidgets.QLabel(Dialog)
        self.manualwindow_label.setObjectName("manualwindow_label")
        self.gridLayout.addWidget(self.manualwindow_label, 2, 0, 1, 2)
        self.numscan_spin = QtWidgets.QSpinBox(Dialog)
        self.numscan_spin.setEnabled(False)
        self.numscan_spin.setObjectName("numscan_spin")
        self.gridLayout.addWidget(self.numscan_spin, 2, 2, 1, 2)
        self.scan_check = QtWidgets.QCheckBox(Dialog)
        self.scan_check.setObjectName("scan_check")
        self.gridLayout.addWidget(self.scan_check, 0, 4, 3, 1)
        self.difforder_spin = QtWidgets.QSpinBox(Dialog)
        self.difforder_spin.setMinimum(1)
        self.difforder_spin.setMaximum(10)
        self.difforder_spin.setObjectName("difforder_spin")
        self.gridLayout.addWidget(self.difforder_spin, 4, 3, 2, 1)
        self.diff_check = QtWidgets.QCheckBox(Dialog)
        self.diff_check.setObjectName("diff_check")
        self.gridLayout.addWidget(self.diff_check, 4, 4, 2, 1)
        self.difforder_label = QtWidgets.QLabel(Dialog)
        self.difforder_label.setObjectName("difforder_label")
        self.gridLayout.addWidget(self.difforder_label, 4, 0, 2, 3)
        self.scanselalgo_combo = QtWidgets.QComboBox(Dialog)
        self.scanselalgo_combo.setObjectName("scanselalgo_combo")
        self.gridLayout.addWidget(self.scanselalgo_combo, 1, 0, 1, 4)
        self.scansel_label = QtWidgets.QLabel(Dialog)
        self.scansel_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scansel_label.setObjectName("scansel_label")
        self.gridLayout.addWidget(self.scansel_label, 0, 0, 1, 4)
        self.gridLayout.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Data Conversion Options"))
        self.manualwindow_label.setText(_translate("Dialog", "Manual Window (# scans)"))
        self.scan_check.setText(_translate("Dialog", "Perform Scan Selection"))
        self.diff_check.setText(_translate("Dialog", "Differentiate Spectra"))
        self.difforder_label.setText(_translate("Dialog", "Order of Differentiation"))
        self.scansel_label.setText(_translate("Dialog", "Scan Selection Algorithm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
